"""Таблица предметов для roguelike.

КАК ДОБАВИТЬ НОВЫЙ ПРЕДМЕТ:
- Добавь новый ключ (уникальный ID) в ITEMS.
- Заполни поля по схеме ниже.

СХЕМА ПОЛЕЙ:
    id            : str          уникальный ключ
    name          : str          настоящее имя (после опознания)
    char          : str          символ на карте
    color         : int/str      цвет curses
    type          : str          категория: potion/scroll/food/artifact/weapon/armor/ring/spellbook/gold
    stackable     : bool         складывается ли в стопку
    value         : int          цена
    effect        : str          ключ эффекта в systems/effects.py
    effect_power  : int/tuple    параметры эффекта
    identified_by_default : bool опознан ли сразу (еда, золото)
    rarity        : str          common/uncommon/rare/legendary
    depth_min     : int          минимальная глубина появления
    tags          : list[str]    теги для биомов (dungeon/cave/hell/fire_themed и т.д.)
    description   : str          описание
"""

from __future__ import annotations

ITEMS: dict[str, dict] = {   'potion_healing': {   'name': 'зелье лечения',
                          'char': '!',
                          'unicode_char': '!',
                          'color': 'red',
                          'type': 'potion',
                          'stackable': True,
                          'value': 15,
                          'effect': 'heal',
                          'effect_power': (8, 15),
                          'identified_by_default': False,
                          'rarity': 'common',
                          'depth_min': 1,
                          'description': 'Восстанавливает здоровье. Алхимики варят это столетиями.',
                          'tags': ['common', 'potion']},
    'potion_healing_major': {   'name': 'большое зелье лечения',
                                'char': '!',
                                'unicode_char': '!',
                                'color': 'red',
                                'type': 'potion',
                                'stackable': True,
                                'value': 40,
                                'effect': 'heal_major',
                                'effect_power': (20, 35),
                                'identified_by_default': False,
                                'rarity': 'uncommon',
                                'depth_min': 3,
                                'description': 'Сильное лечебное зелье для тяжёлых ран.',
                                'tags': ['potion', 'uncommon']},
    'potion_mana': {   'name': 'зелье маны',
                       'char': '!',
                       'unicode_char': '!',
                       'color': 'blue',
                       'type': 'potion',
                       'stackable': True,
                       'value': 20,
                       'effect': 'restore_mana',
                       'effect_power': (5, 10),
                       'identified_by_default': False,
                       'rarity': 'common',
                       'depth_min': 2,
                       'description': 'Восстанавливает магическую энергию.',
                       'tags': ['common', 'mana', 'potion']},
    'potion_strength': {   'name': 'зелье силы',
                           'char': '!',
                           'unicode_char': '!',
                           'color': 'red',
                           'type': 'potion',
                           'stackable': True,
                           'value': 60,
                           'effect': 'strength',
                           'effect_power': 1,
                           'identified_by_default': False,
                           'rarity': 'rare',
                           'depth_min': 4,
                           'description': 'Навсегда увеличивает урон.',
                           'tags': ['potion', 'rare']},
    'potion_max_hp': {   'name': 'зелье стойкости',
                         'char': '!',
                         'unicode_char': '!',
                         'color': 'red',
                         'type': 'potion',
                         'stackable': True,
                         'value': 50,
                         'effect': 'max_hp',
                         'effect_power': 5,
                         'identified_by_default': False,
                         'rarity': 'rare',
                         'depth_min': 4,
                         'description': 'Навсегда увеличивает максимальное здоровье.',
                         'tags': ['potion', 'rare']},
    'potion_speed': {   'name': 'зелье скорости',
                        'char': '!',
                        'unicode_char': '!',
                        'color': 'green',
                        'type': 'potion',
                        'stackable': True,
                        'value': 35,
                        'effect': 'speed',
                        'effect_power': 3,
                        'identified_by_default': False,
                        'rarity': 'uncommon',
                        'depth_min': 3,
                        'description': 'На время ускоряет ваши движения.',
                        'tags': ['potion', 'uncommon']},
    'potion_invisibility': {   'name': 'зелье невидимости',
                               'char': '!',
                               'unicode_char': '!',
                               'color': 'cyan',
                               'type': 'potion',
                               'stackable': True,
                               'value': 45,
                               'effect': 'invisibility',
                               'effect_power': 10,
                               'identified_by_default': False,
                               'rarity': 'rare',
                               'depth_min': 4,
                               'description': 'Делает вас невидимым для врагов.',
                               'tags': ['potion', 'rare']},
    'potion_levitation': {   'name': 'зелье левитации',
                             'char': '!',
                             'unicode_char': '!',
                             'color': 'cyan',
                             'type': 'potion',
                             'stackable': True,
                             'value': 30,
                             'effect': 'levitation',
                             'effect_power': 15,
                             'identified_by_default': False,
                             'rarity': 'uncommon',
                             'depth_min': 3,
                             'description': 'Вы парите над землёй, игнорируя ловушки.',
                             'tags': ['potion', 'uncommon']},
    'potion_fire_breath': {   'name': 'зелье огненного дыхания',
                              'char': '!',
                              'unicode_char': '!',
                              'color': 'red',
                              'type': 'potion',
                              'stackable': True,
                              'value': 40,
                              'effect': 'fire_breath',
                              'effect_power': (10, 18),
                              'identified_by_default': False,
                              'rarity': 'uncommon',
                              'depth_min': 3,
                              'description': 'Позволяет выдохнуть пламя.',
                              'tags': ['fire_themed', 'potion', 'uncommon']},
    'potion_confusion': {   'name': 'зелье спутанности',
                            'char': '!',
                            'unicode_char': '!',
                            'color': 'magenta',
                            'type': 'potion',
                            'stackable': True,
                            'value': 10,
                            'effect': 'confusion',
                            'effect_power': 5,
                            'identified_by_default': False,
                            'rarity': 'common',
                            'depth_min': 1,
                            'description': 'Вредное зелье, путающее управление.',
                            'tags': ['common', 'potion']},
    'potion_blindness': {   'name': 'зелье слепоты',
                            'char': '!',
                            'unicode_char': '!',
                            'color': 'black',
                            'type': 'potion',
                            'stackable': True,
                            'value': 10,
                            'effect': 'blindness',
                            'effect_power': 10,
                            'identified_by_default': False,
                            'rarity': 'common',
                            'depth_min': 1,
                            'description': 'Вредное зелье, ослепляющее на время.',
                            'tags': ['common', 'potion']},
    'potion_experience': {   'name': 'зелье опыта',
                             'char': '!',
                             'unicode_char': '!',
                             'color': 'yellow',
                             'type': 'potion',
                             'stackable': True,
                             'value': 80,
                             'effect': 'experience',
                             'effect_power': 50,
                             'identified_by_default': False,
                             'rarity': 'rare',
                             'depth_min': 5,
                             'description': 'Наполняет вас знаниями и опытом.',
                             'tags': ['potion', 'rare']},
    'scroll_identify': {   'name': 'свиток опознания',
                           'char': '?',
                           'unicode_char': '?',
                           'color': 'white',
                           'type': 'scroll',
                           'stackable': True,
                           'value': 30,
                           'effect': 'identify',
                           'effect_power': None,
                           'identified_by_default': False,
                           'rarity': 'common',
                           'depth_min': 1,
                           'description': 'Позволяет опознать один предмет.',
                           'tags': ['common', 'scroll']},
    'scroll_mapping': {   'name': 'свиток карты',
                          'char': '?',
                          'unicode_char': '?',
                          'color': 'white',
                          'type': 'scroll',
                          'stackable': True,
                          'value': 35,
                          'effect': 'mapping',
                          'effect_power': None,
                          'identified_by_default': False,
                          'rarity': 'uncommon',
                          'depth_min': 2,
                          'description': 'Открывает всю карту текущего уровня.',
                          'tags': ['scroll', 'uncommon']},
    'scroll_teleport': {   'name': 'свиток телепорта',
                           'char': '?',
                           'unicode_char': '?',
                           'color': 'white',
                           'type': 'scroll',
                           'stackable': True,
                           'value': 30,
                           'effect': 'teleport',
                           'effect_power': None,
                           'identified_by_default': False,
                           'rarity': 'common',
                           'depth_min': 2,
                           'description': 'Телепортирует в случайное место уровня.',
                           'tags': ['common', 'scroll']},
    'scroll_magic_missile': {   'name': 'свиток магической стрелы',
                                'char': '?',
                                'unicode_char': '?',
                                'color': 'white',
                                'type': 'scroll',
                                'stackable': True,
                                'value': 25,
                                'effect': 'magic_missile',
                                'effect_power': (8, 14),
                                'identified_by_default': False,
                                'rarity': 'common',
                                'depth_min': 1,
                                'description': 'Выпускает магическую стрелу в случайного видимого врага.',
                                'tags': ['common', 'scroll']},
    'scroll_summon_ally': {   'name': 'свиток призыва союзника',
                              'char': '?',
                              'unicode_char': '?',
                              'color': 'white',
                              'type': 'scroll',
                              'stackable': True,
                              'value': 50,
                              'effect': 'summon_ally',
                              'effect_power': 10,
                              'identified_by_default': False,
                              'rarity': 'uncommon',
                              'depth_min': 3,
                              'description': 'Призывает дружественную силу на несколько ходов.',
                              'tags': ['crypt', 'scroll', 'uncommon']},
    'scroll_remove_curse': {   'name': 'свиток снятия проклятия',
                               'char': '?',
                               'unicode_char': '?',
                               'color': 'white',
                               'type': 'scroll',
                               'stackable': True,
                               'value': 60,
                               'effect': 'remove_curse',
                               'effect_power': None,
                               'identified_by_default': False,
                               'rarity': 'uncommon',
                               'depth_min': 3,
                               'description': 'Снимает проклятие с экипированной вещи.',
                               'tags': ['crypt', 'scroll', 'uncommon']},
    'scroll_enchant_weapon': {   'name': 'свиток зачарования оружия',
                                 'char': '?',
                                 'unicode_char': '?',
                                 'color': 'white',
                                 'type': 'scroll',
                                 'stackable': True,
                                 'value': 70,
                                 'effect': 'enchant_weapon',
                                 'effect_power': None,
                                 'identified_by_default': False,
                                 'rarity': 'rare',
                                 'depth_min': 4,
                                 'description': 'Улучшает экипированное оружие.',
                                 'tags': ['rare', 'scroll']},
    'scroll_enchant_armor': {   'name': 'свиток зачарования брони',
                                'char': '?',
                                'unicode_char': '?',
                                'color': 'white',
                                'type': 'scroll',
                                'stackable': True,
                                'value': 70,
                                'effect': 'enchant_armor',
                                'effect_power': None,
                                'identified_by_default': False,
                                'rarity': 'rare',
                                'depth_min': 4,
                                'description': 'Улучшает экипированную броню.',
                                'tags': ['rare', 'scroll']},
    'scroll_fireball': {   'name': 'свиток огненного шара',
                           'char': '?',
                           'unicode_char': '?',
                           'color': 'white',
                           'type': 'scroll',
                           'stackable': True,
                           'value': 55,
                           'effect': 'fireball',
                           'effect_power': (12, 20),
                           'identified_by_default': False,
                           'rarity': 'uncommon',
                           'depth_min': 3,
                           'description': 'Взрывается огненным шаром вокруг вас.',
                           'tags': ['fire_themed', 'hell', 'scroll', 'uncommon']},
    'scroll_freeze': {   'name': 'свиток заморозки',
                         'char': '?',
                         'unicode_char': '?',
                         'color': 'white',
                         'type': 'scroll',
                         'stackable': True,
                         'value': 50,
                         'effect': 'freeze',
                         'effect_power': 3,
                         'identified_by_default': False,
                         'rarity': 'uncommon',
                         'depth_min': 3,
                         'description': 'Парализует льдом всех видимых врагов.',
                         'tags': ['ice_themed', 'scroll', 'uncommon']},
    'bread': {   'name': 'краюха хлеба',
                 'char': '%',
                 'unicode_char': '%',
                 'color': 'yellow',
                 'type': 'food',
                 'stackable': True,
                 'value': 5,
                 'effect': 'food',
                 'effect_power': 30,
                 'identified_by_default': True,
                 'rarity': 'common',
                 'depth_min': 1,
                 'description': 'Сытная краюха хлеба.',
                 'tags': ['common', 'food']},
    'meat': {   'name': 'кусок мяса',
                'char': '%',
                'unicode_char': '%',
                'color': 'red',
                'type': 'food',
                'stackable': True,
                'value': 10,
                'effect': 'food',
                'effect_power': 50,
                'identified_by_default': True,
                'rarity': 'common',
                'depth_min': 1,
                'description': 'Сырое или жареное мясо.',
                'tags': ['common', 'food']},
    'elven_bread': {   'name': 'эльфийский хлеб',
                       'char': '%',
                       'unicode_char': '%',
                       'color': 'green',
                       'type': 'food',
                       'stackable': True,
                       'value': 25,
                       'effect': 'food',
                       'effect_power': 80,
                       'identified_by_default': True,
                       'rarity': 'uncommon',
                       'depth_min': 2,
                       'description': 'Питательный эльфийский хлеб.',
                       'tags': ['food', 'uncommon']},
    'mushroom': {   'name': 'подозрительный гриб',
                    'char': '%',
                    'unicode_char': '%',
                    'color': 'magenta',
                    'type': 'food',
                    'stackable': True,
                    'value': 5,
                    'effect': 'suspicious_food',
                    'effect_power': 20,
                    'identified_by_default': True,
                    'rarity': 'common',
                    'depth_min': 1,
                    'description': 'Может быть съедобным, а может быть ядовитым.',
                    'tags': ['cave', 'common', 'food']},
    'ration': {   'name': 'сухой паёк',
                  'char': '%',
                  'unicode_char': '%',
                  'color': 'yellow',
                  'type': 'food',
                  'stackable': True,
                  'value': 8,
                  'effect': 'food',
                  'effect_power': 40,
                  'identified_by_default': True,
                  'rarity': 'common',
                  'depth_min': 1,
                  'description': 'Сухпайок для путешественников.',
                  'tags': ['common', 'food']},
    'amulet_of_life': {   'name': 'амулет жизни',
                          'char': '"',
                          'unicode_char': '"',
                          'color': 'red',
                          'type': 'artifact',
                          'stackable': False,
                          'value': 500,
                          'effect': 'artifact',
                          'effect_power': {'bonus': 'max_hp', 'value': 30},
                          'identified_by_default': True,
                          'rarity': 'legendary',
                          'depth_min': 5,
                          'description': 'Увеличивает максимальное здоровье на 30.',
                          'tags': ['artifact', 'deep', 'legendary']},
    'crown_of_wisdom': {   'name': 'корона мудрости',
                           'char': '"',
                           'unicode_char': '"',
                           'color': 'yellow',
                           'type': 'artifact',
                           'stackable': False,
                           'value': 500,
                           'effect': 'artifact',
                           'effect_power': {'bonus': 'xp_bonus', 'value': 50},
                           'identified_by_default': True,
                           'rarity': 'legendary',
                           'depth_min': 5,
                           'description': 'Получаемый опыт увеличен на 50%.',
                           'tags': ['artifact', 'deep', 'legendary']},
    'boots_of_wind': {   'name': 'сапоги ветра',
                         'char': '"',
                         'unicode_char': '"',
                         'color': 'cyan',
                         'type': 'artifact',
                         'stackable': False,
                         'value': 500,
                         'effect': 'artifact',
                         'effect_power': {'bonus': 'speed', 'value': 1},
                         'identified_by_default': True,
                         'rarity': 'legendary',
                         'depth_min': 5,
                         'description': 'Повышают скорость передвижения.',
                         'tags': ['artifact', 'deep', 'legendary']},
    'eye_of_truth': {   'name': 'око истины',
                        'char': '"',
                        'unicode_char': '"',
                        'color': 'blue',
                        'type': 'artifact',
                        'stackable': False,
                        'value': 500,
                        'effect': 'artifact',
                        'effect_power': {'bonus': 'fov', 'value': 3},
                        'identified_by_default': True,
                        'rarity': 'legendary',
                        'depth_min': 5,
                        'description': 'Увеличивает радиус обзора и позволяет видеть ловушки.',
                        'tags': ['artifact', 'deep', 'legendary']},
    'heart_of_dragon': {   'name': 'сердце дракона',
                           'char': '"',
                           'unicode_char': '"',
                           'color': 'red',
                           'type': 'artifact',
                           'stackable': False,
                           'value': 600,
                           'effect': 'artifact',
                           'effect_power': {'bonus': 'fire_immune', 'value': 1},
                           'identified_by_default': True,
                           'rarity': 'legendary',
                           'depth_min': 6,
                           'description': 'Даёт иммунитет к огню и усиливает огненный урон.',
                           'tags': ['artifact', 'deep', 'hell', 'legendary']},
    'dagger': {   'name': 'кинжал',
                  'char': '/',
                  'unicode_char': '/',
                  'color': 'white',
                  'type': 'weapon',
                  'stackable': False,
                  'value': 10,
                  'effect': 'weapon_id',
                  'effect_power': 'dagger',
                  'identified_by_default': True,
                  'rarity': 'common',
                  'depth_min': 1,
                  'description': 'Лёгкое и острое лезвие.',
                  'tags': ['common', 'dungeon', 'equipment', 'weapon']},
    'short_sword': {   'name': 'короткий меч',
                       'char': '/',
                       'unicode_char': '/',
                       'color': 'white',
                       'type': 'weapon',
                       'stackable': False,
                       'value': 25,
                       'effect': 'weapon_id',
                       'effect_power': 'short_sword',
                       'identified_by_default': True,
                       'rarity': 'common',
                       'depth_min': 1,
                       'description': 'Надёжный клинок для начинающих искателей приключений.',
                       'tags': ['common', 'dungeon', 'equipment', 'weapon']},
    'long_sword': {   'name': 'длинный меч',
                      'char': '/',
                      'unicode_char': '/',
                      'color': 'white',
                      'type': 'weapon',
                      'stackable': False,
                      'value': 45,
                      'effect': 'weapon_id',
                      'effect_power': 'long_sword',
                      'identified_by_default': True,
                      'rarity': 'common',
                      'depth_min': 2,
                      'description': 'Сбалансированное оружие.',
                      'tags': ['common', 'dungeon', 'equipment', 'weapon']},
    'spear': {   'name': 'копьё',
                 'char': '-',
                 'unicode_char': '/',
                 'color': 'white',
                 'type': 'weapon',
                 'stackable': False,
                 'value': 40,
                 'effect': 'weapon_id',
                 'effect_power': 'spear',
                 'identified_by_default': True,
                 'rarity': 'common',
                 'depth_min': 2,
                 'description': 'Позволяет держать врага на расстоянии.',
                 'tags': ['common', 'dungeon', 'equipment', 'weapon']},
    'mace': {   'name': 'булава',
                'char': '|',
                'unicode_char': '/',
                'color': 'white',
                'type': 'weapon',
                'stackable': False,
                'value': 35,
                'effect': 'weapon_id',
                'effect_power': 'mace',
                'identified_by_default': True,
                'rarity': 'common',
                'depth_min': 2,
                'description': 'Оружие с шипастой головой.',
                'tags': ['common', 'dungeon', 'equipment', 'weapon']},
    'rapier': {   'name': 'рапира',
                  'char': '/',
                  'unicode_char': '/',
                  'color': 'green',
                  'type': 'weapon',
                  'stackable': False,
                  'value': 80,
                  'effect': 'weapon_id',
                  'effect_power': 'rapier',
                  'identified_by_default': True,
                  'rarity': 'uncommon',
                  'depth_min': 3,
                  'description': 'Тонкий клинок для точных уколов.',
                  'tags': ['equipment', 'uncommon', 'weapon']},
    'greatsword': {   'name': 'двуручный меч',
                      'char': '/',
                      'unicode_char': '/',
                      'color': 'blue',
                      'type': 'weapon',
                      'stackable': False,
                      'value': 150,
                      'effect': 'weapon_id',
                      'effect_power': 'greatsword',
                      'identified_by_default': True,
                      'rarity': 'rare',
                      'depth_min': 4,
                      'description': 'Массивный разрушительный меч.',
                      'tags': ['equipment', 'rare', 'weapon']},
    'warhammer': {   'name': 'боевой молот',
                     'char': '|',
                     'unicode_char': '/',
                     'color': 'blue',
                     'type': 'weapon',
                     'stackable': False,
                     'value': 140,
                     'effect': 'weapon_id',
                     'effect_power': 'warhammer',
                     'identified_by_default': True,
                     'rarity': 'rare',
                     'depth_min': 4,
                     'description': 'Двуручный молот.',
                     'tags': ['equipment', 'rare', 'weapon']},
    'poisoned_blade': {   'name': 'отравленный клинок',
                          'char': '/',
                          'unicode_char': '/',
                          'color': 'green',
                          'type': 'weapon',
                          'stackable': False,
                          'value': 100,
                          'effect': 'weapon_id',
                          'effect_power': 'poisoned_blade',
                          'identified_by_default': True,
                          'rarity': 'uncommon',
                          'depth_min': 3,
                          'description': 'Покрыт ядом.',
                          'tags': ['equipment', 'poison_themed', 'uncommon', 'weapon']},
    'flaming_sword': {   'name': 'огненный меч',
                         'char': '/',
                         'unicode_char': '/',
                         'color': 'red',
                         'type': 'weapon',
                         'stackable': False,
                         'value': 180,
                         'effect': 'weapon_id',
                         'effect_power': 'flaming_sword',
                         'identified_by_default': True,
                         'rarity': 'rare',
                         'depth_min': 4,
                         'description': 'Клинок, пылающий магическим огнём.',
                         'tags': ['equipment', 'fire_themed', 'hell', 'rare', 'weapon']},
    'vampiric_dagger': {   'name': 'вампирский кинжал',
                           'char': '/',
                           'unicode_char': '/',
                           'color': 'magenta',
                           'type': 'weapon',
                           'stackable': False,
                           'value': 170,
                           'effect': 'weapon_id',
                           'effect_power': 'vampiric_dagger',
                           'identified_by_default': True,
                           'rarity': 'rare',
                           'depth_min': 4,
                           'description': 'Восстанавливает здоровье при ударах.',
                           'tags': ['equipment', 'rare', 'weapon']},
    'frost_axe': {   'name': 'ледяной топор',
                     'char': '|',
                     'unicode_char': '/',
                     'color': 'cyan',
                     'type': 'weapon',
                     'stackable': False,
                     'value': 190,
                     'effect': 'weapon_id',
                     'effect_power': 'frost_axe',
                     'identified_by_default': True,
                     'rarity': 'rare',
                     'depth_min': 5,
                     'description': 'Покрыт инеем.',
                     'tags': ['equipment', 'ice_themed', 'rare', 'weapon']},
    'cursed_blade': {   'name': 'проклятый клинок',
                        'char': '/',
                        'unicode_char': '/',
                        'color': 'red',
                        'type': 'weapon',
                        'stackable': False,
                        'value': 300,
                        'effect': 'weapon_id',
                        'effect_power': 'cursed_blade',
                        'identified_by_default': True,
                        'rarity': 'legendary',
                        'depth_min': 5,
                        'description': 'Мощное, но проклятое оружие.',
                        'tags': ['deep', 'equipment', 'legendary', 'weapon']},
    'leather_armor': {   'name': 'кожаный доспех',
                         'char': '[',
                         'unicode_char': '[',
                         'color': 'yellow',
                         'type': 'armor',
                         'stackable': False,
                         'value': 20,
                         'effect': 'armor_id',
                         'effect_power': 'leather_armor',
                         'identified_by_default': True,
                         'rarity': 'common',
                         'depth_min': 1,
                         'description': 'Грубая кожа, но лучше, чем ничего.',
                         'tags': ['armor', 'common', 'dungeon', 'equipment']},
    'studded_leather': {   'name': 'доспех с клепками',
                           'char': '[',
                           'unicode_char': '[',
                           'color': 'yellow',
                           'type': 'armor',
                           'stackable': False,
                           'value': 40,
                           'effect': 'armor_id',
                           'effect_power': 'studded_leather',
                           'identified_by_default': True,
                           'rarity': 'common',
                           'depth_min': 2,
                           'description': 'Кожа, усиленная металлическими клепками.',
                           'tags': ['armor', 'common', 'dungeon', 'equipment']},
    'chain_shirt': {   'name': 'кольчужная рубаха',
                       'char': '[',
                       'unicode_char': '[',
                       'color': 'green',
                       'type': 'armor',
                       'stackable': False,
                       'value': 80,
                       'effect': 'armor_id',
                       'effect_power': 'chain_shirt',
                       'identified_by_default': True,
                       'rarity': 'uncommon',
                       'depth_min': 3,
                       'description': 'Лёгкая кольчуга.',
                       'tags': ['armor', 'dungeon', 'equipment', 'uncommon']},
    'scale_mail': {   'name': 'чешуйчатый доспех',
                      'char': '[',
                      'unicode_char': '[',
                      'color': 'green',
                      'type': 'armor',
                      'stackable': False,
                      'value': 100,
                      'effect': 'armor_id',
                      'effect_power': 'scale_mail',
                      'identified_by_default': True,
                      'rarity': 'uncommon',
                      'depth_min': 3,
                      'description': 'Металлические чешуйки.',
                      'tags': ['armor', 'dungeon', 'equipment', 'uncommon']},
    'breastplate': {   'name': 'нагрудник',
                       'char': '[',
                       'unicode_char': '[',
                       'color': 'blue',
                       'type': 'armor',
                       'stackable': False,
                       'value': 160,
                       'effect': 'armor_id',
                       'effect_power': 'breastplate',
                       'identified_by_default': True,
                       'rarity': 'rare',
                       'depth_min': 4,
                       'description': 'Прочная металлическая грудная пластина.',
                       'tags': ['armor', 'dungeon', 'equipment', 'rare']},
    'plate_armor': {   'name': 'рыцарские латы',
                       'char': '[',
                       'unicode_char': '[',
                       'color': 'yellow',
                       'type': 'armor',
                       'stackable': False,
                       'value': 300,
                       'effect': 'armor_id',
                       'effect_power': 'plate_armor',
                       'identified_by_default': True,
                       'rarity': 'legendary',
                       'depth_min': 6,
                       'description': 'Полный комплект латов.',
                       'tags': ['armor', 'dungeon', 'equipment', 'legendary']},
    'cursed_plate': {   'name': 'проклятые латы',
                        'char': '[',
                        'unicode_char': '[',
                        'color': 'red',
                        'type': 'armor',
                        'stackable': False,
                        'value': 400,
                        'effect': 'armor_id',
                        'effect_power': 'cursed_plate',
                        'identified_by_default': True,
                        'rarity': 'legendary',
                        'depth_min': 6,
                        'description': 'Невероятно прочные, но проклятые латы.',
                        'tags': ['armor', 'deep', 'dungeon', 'equipment', 'legendary']},
    'ring_of_health': {   'name': 'кольцо здоровья',
                          'char': '=',
                          'unicode_char': '=',
                          'color': 'red',
                          'type': 'ring',
                          'stackable': False,
                          'value': 80,
                          'effect': 'ring_hp',
                          'effect_power': {'bonus': 'hp', 'value': 10, 'cursed': False},
                          'identified_by_default': True,
                          'rarity': 'uncommon',
                          'depth_min': 2,
                          'description': 'Увеличивает максимальное здоровье.',
                          'tags': ['ring', 'uncommon']},
    'ring_of_strength': {   'name': 'кольцо силы',
                            'char': '=',
                            'unicode_char': '=',
                            'color': 'red',
                            'type': 'ring',
                            'stackable': False,
                            'value': 100,
                            'effect': 'ring_atk',
                            'effect_power': {'bonus': 'atk', 'value': 2, 'cursed': False},
                            'identified_by_default': True,
                            'rarity': 'uncommon',
                            'depth_min': 2,
                            'description': 'Увеличивает урон в бою.',
                            'tags': ['ring', 'uncommon']},
    'ring_of_protection': {   'name': 'кольцо защиты',
                              'char': '=',
                              'unicode_char': '=',
                              'color': 'cyan',
                              'type': 'ring',
                              'stackable': False,
                              'value': 90,
                              'effect': 'ring_def',
                              'effect_power': {'bonus': 'def', 'value': 2, 'cursed': False},
                              'identified_by_default': True,
                              'rarity': 'uncommon',
                              'depth_min': 2,
                              'description': 'Снижает получаемый урон.',
                              'tags': ['ring', 'uncommon']},
    'ring_of_swiftness': {   'name': 'кольцо скорости',
                             'char': '=',
                             'unicode_char': '=',
                             'color': 'green',
                             'type': 'ring',
                             'stackable': False,
                             'value': 120,
                             'effect': 'ring_speed',
                             'effect_power': {'bonus': 'speed', 'value': 1, 'cursed': False},
                             'identified_by_default': True,
                             'rarity': 'uncommon',
                             'depth_min': 3,
                             'description': 'Позволяет ходить чаще.',
                             'tags': ['ring', 'uncommon']},
    'ring_of_fortune': {   'name': 'кольцо удачи',
                           'char': '=',
                           'unicode_char': '=',
                           'color': 'yellow',
                           'type': 'ring',
                           'stackable': False,
                           'value': 110,
                           'effect': 'ring_luck',
                           'effect_power': {'bonus': 'luck', 'value': 10, 'cursed': False},
                           'identified_by_default': True,
                           'rarity': 'uncommon',
                           'depth_min': 3,
                           'description': 'Увеличивает шанс выпадения лута.',
                           'tags': ['ring', 'uncommon']},
    'cursed_ring': {   'name': 'проклятое кольцо',
                       'char': '=',
                       'unicode_char': '=',
                       'color': 'red',
                       'type': 'ring',
                       'stackable': False,
                       'value': 50,
                       'effect': 'ring_cursed',
                       'effect_power': {'bonus': 'hp', 'value': -5, 'cursed': True},
                       'identified_by_default': True,
                       'rarity': 'uncommon',
                       'depth_min': 2,
                       'description': 'Проклятый артефакт. Нельзя снять.',
                       'tags': ['ring', 'uncommon']},
    'spellbook_fireball': {   'name': 'книга огненного шара',
                              'char': '+',
                              'unicode_char': '+',
                              'color': 'red',
                              'type': 'spellbook',
                              'stackable': False,
                              'value': 120,
                              'effect': 'learn_spell',
                              'effect_power': 'fireball',
                              'teaches': 'fireball',
                              'identified_by_default': True,
                              'rarity': 'rare',
                              'depth_min': 3,
                              'description': "Учит заклинанию 'огненный шар'.",
                              'tags': ['fire_themed', 'hell', 'rare', 'spellbook']},
    'spellbook_lightning': {   'name': 'книга молнии',
                               'char': '+',
                               'unicode_char': '+',
                               'color': 'yellow',
                               'type': 'spellbook',
                               'stackable': False,
                               'value': 100,
                               'effect': 'learn_spell',
                               'effect_power': 'lightning_bolt',
                               'teaches': 'lightning_bolt',
                               'identified_by_default': True,
                               'rarity': 'uncommon',
                               'depth_min': 2,
                               'description': "Учит заклинанию 'удар молнии'.",
                               'tags': ['lightning_themed', 'spellbook', 'uncommon']},
    'spellbook_ice_bolt': {   'name': 'книга ледяной стрелы',
                              'char': '+',
                              'unicode_char': '+',
                              'color': 'cyan',
                              'type': 'spellbook',
                              'stackable': False,
                              'value': 90,
                              'effect': 'learn_spell',
                              'effect_power': 'ice_bolt',
                              'teaches': 'ice_bolt',
                              'identified_by_default': True,
                              'rarity': 'uncommon',
                              'depth_min': 2,
                              'description': "Учит заклинанию 'ледяная стрела'.",
                              'tags': ['ice_themed', 'spellbook', 'uncommon']},
    'spellbook_barrier': {   'name': 'книга магического барьера',
                             'char': '+',
                             'unicode_char': '+',
                             'color': 'blue',
                             'type': 'spellbook',
                             'stackable': False,
                             'value': 80,
                             'effect': 'learn_spell',
                             'effect_power': 'barrier',
                             'teaches': 'barrier',
                             'identified_by_default': True,
                             'rarity': 'uncommon',
                             'depth_min': 2,
                             'description': "Учит заклинанию 'магический барьер'.",
                             'tags': ['spellbook', 'uncommon']},
    'spellbook_haste': {   'name': 'книга ускорения',
                           'char': '+',
                           'unicode_char': '+',
                           'color': 'green',
                           'type': 'spellbook',
                           'stackable': False,
                           'value': 85,
                           'effect': 'learn_spell',
                           'effect_power': 'haste',
                           'teaches': 'haste',
                           'identified_by_default': True,
                           'rarity': 'uncommon',
                           'depth_min': 2,
                           'description': "Учит заклинанию 'ускорение'.",
                           'tags': ['spellbook', 'uncommon']},
    'spellbook_invisibility': {   'name': 'книга невидимости',
                                  'char': '+',
                                  'unicode_char': '+',
                                  'color': 'magenta',
                                  'type': 'spellbook',
                                  'stackable': False,
                                  'value': 150,
                                  'effect': 'learn_spell',
                                  'effect_power': 'invisibility',
                                  'teaches': 'invisibility',
                                  'identified_by_default': True,
                                  'rarity': 'rare',
                                  'depth_min': 4,
                                  'description': "Учит заклинанию 'невидимость'.",
                                  'tags': ['rare', 'spellbook']},
    'spellbook_teleport': {   'name': 'книга телепорта',
                              'char': '+',
                              'unicode_char': '+',
                              'color': 'magenta',
                              'type': 'spellbook',
                              'stackable': False,
                              'value': 110,
                              'effect': 'learn_spell',
                              'effect_power': 'teleport_spell',
                              'teaches': 'teleport_spell',
                              'identified_by_default': True,
                              'rarity': 'uncommon',
                              'depth_min': 3,
                              'description': "Учит заклинанию 'телепорт'.",
                              'tags': ['spellbook', 'uncommon']},
    'gold': {   'name': 'золото',
                'char': '$',
                'unicode_char': '$',
                'color': 'yellow',
                'type': 'gold',
                'stackable': True,
                'value': 1,
                'effect': 'none',
                'effect_power': None,
                'identified_by_default': True,
                'rarity': 'common',
                'depth_min': 1,
                'description': 'Блестящие монеты.',
                'tags': ['common', 'gold']},
    'prisoner_key': {
                'name': 'ключ от клетки',
                'char': 'K',
                'unicode_char': '🗝',
                'type': 'key',
                'value': 5,
                'identified_by_default': True,
                'rarity': 'common',
                'depth_min': 1,
                'description': 'Ржавый ключ от двери пленника.',
                'tags': ['common', 'key']}}

def get_item(item_id: str) -> dict | None:
    return ITEMS.get(item_id)


def items_for_depth(depth: int) -> list[str]:
    """Вернуть ID предметов, подходящих для глубины."""
    result = []
    for iid, data in ITEMS.items():
        if iid == "gold":
            continue
        if data.get("depth_min", 1) > depth:
            continue
        # Артефакты очень редкие
        if data["type"] == "artifact" and __import__("random").random() > 0.1:
            continue
        result.append(iid)
    return result


def items_for_biome(biome_tags: list[str], depth: int) -> list[str]:
    """Вернуть ID предметов, подходящих для биома и глубины."""
    result = []
    biome_set = set(biome_tags)
    for iid, data in ITEMS.items():
        if iid == "gold":
            continue
        if data.get("depth_min", 1) > depth:
            continue
        item_tags = set(data.get("tags", []))
        if not (item_tags & biome_set):
            continue
        if data["type"] == "artifact" and __import__("random").random() > 0.1:
            continue
        result.append(iid)
    return result if result else items_for_depth(depth)


def get_equipment_details(item_id: str) -> dict | None:
    """Получить базовые характеристики экипировки (оружие/броня)."""
    data = get_item(item_id)
    if not data:
        return None
    if data["type"] == "weapon":
        from content.weapons import get_weapon
        return get_weapon(data["effect_power"])
    if data["type"] == "armor":
        from content.armor import get_armor
        return get_armor(data["effect_power"])
    return None
