"""Таблица монстров для roguelike.

КАК ДОБАВИТЬ НОВОГО МОНСТРА:
- Добавь новый ключ (уникальный ID) в MONSTERS.
- Заполни поля по схеме ниже.

СХЕМА ПОЛЕЙ:
    id           : str          уникальный ключ (используется в коде)
    char         : str          символ на карте (1 символ)
    name         : str          отображаемое имя (именительный падеж)
    color        : str          имя цвета curses (green/red/yellow/cyan/magenta/blue/white)
    hp           : int          базовое здоровье
    atk          : int          бонус к урону
    dmg          : tuple[int]   кубики урона: (количество, грань, бонус)
    ac           : int          класс брони
    speed        : float        скорость хода (1.0 = как игрок, 0.5 = раз в 2 хода, 2.0 = 2 хода подряд)
    xp           : int          опыт за убийство
    ai           : str          тип ИИ (см. entities/ai.py)
    gold         : tuple[int]   диапазон выпадаемого золота (min, max)
    loot_chance  : float        шанс дропа предмета (0.0 - 1.0)
    loot_table   : list[str]    ID предметов из content/items.py, которые могут выпасть
    depth        : int          минимальная глубина появления
    biome        : str          биом для будущей генерации
    description  : str          описание для бестиария
    tags         : list[str]    теги (undead, flying, poisonous, dungeon, cave, hell и т.д.)
"""

from __future__ import annotations

MONSTERS: dict[str, dict] = {   'rat': {   'char': 'r',
'unicode_char': '🐀',
               'name': 'гигантская крыса',
               'color': 'yellow',
               'hp': 6,
               'atk': 0,
               'dmg': (1, 3, 0),
               'ac': 0,
               'speed': 1.0,
               'xp': 3,
               'ai': 'WANDERING',
               'gold': (0, 2),
               'loot_chance': 0.0,
               'loot_table': [],
               'depth': 1,
               'biome': 'sewers',
               'description': 'Злобная крыса размером с собаку. Не слишком опасна, но надоедлива.',
               'tags': ['beast', 'dungeon', 'sewers']},
    'goblin': {   'char': 'g',
    'unicode_char': '👺',
                  'name': 'гоблин',
                  'color': 'green',
                  'hp': 9,
                  'atk': 1,
                  'dmg': (1, 4, 0),
                  'ac': 1,
                  'speed': 1.0,
                  'xp': 6,
                  'ai': 'AGGRESSIVE',
                  'gold': (1, 4),
                  'loot_chance': 0.1,
                  'loot_table': ['potion_healing', 'dagger'],
                  'depth': 1,
                  'biome': 'dungeon',
                  'description': 'Мелкий зелёный грабитель. Любит численным превосходством.',
                  'tags': ['humanoid', 'dungeon']},
    'bat': {   'char': 'b',
    'unicode_char': '🦇',
               'name': 'летучая мышь',
               'color': 'white',
               'hp': 4,
               'atk': 0,
               'dmg': (1, 2, 0),
               'ac': 0,
               'speed': 1.5,
               'xp': 2,
               'ai': 'WANDERING',
               'gold': (0, 1),
               'loot_chance': 0.0,
               'loot_table': [],
               'depth': 1,
               'biome': 'caves',
               'description': 'Быстрая и раздражающая. Не наносит много урона.',
               'tags': ['beast', 'cave', 'flying']},
    'orc': {   'char': 'o',
    'unicode_char': '👹',
               'name': 'орк',
               'color': 'green',
               'hp': 18,
               'atk': 2,
               'dmg': (1, 6, 1),
               'ac': 2,
               'speed': 1.0,
               'xp': 12,
               'ai': 'AGGRESSIVE',
               'gold': (2, 8),
               'loot_chance': 0.15,
               'loot_table': ['potion_healing', 'short_sword', 'leather_armor'],
               'depth': 2,
               'biome': 'dungeon',
               'description': 'Грубый воин с дубиной. Крепче и злее гоблина.',
               'tags': ['humanoid', 'dungeon']},
    'snake': {   'char': 's',
    'unicode_char': '🐍',
                 'name': 'ядовитая змея',
                 'color': 'yellow',
                 'hp': 10,
                 'atk': 1,
                 'dmg': (1, 3, 0),
                 'ac': 0,
                 'speed': 1.0,
                 'xp': 7,
                 'ai': 'COWARDLY',
                 'gold': (0, 3),
                 'loot_chance': 0.1,
                 'loot_table': ['potion_healing'],
                 'depth': 2,
                 'biome': 'sewers',
                 'description': 'Её укус отравляет кровь. При ранении старается уползти.',
                 'tags': ['beast', 'cave', 'poisonous']},
    'skeleton': {   'char': 'S',
    'unicode_char': '💀',
                    'name': 'скелет',
                    'color': 'white',
                    'hp': 14,
                    'atk': 1,
                    'dmg': (1, 5, 0),
                    'ac': 1,
                    'speed': 0.8,
                    'xp': 9,
                    'ai': 'AGGRESSIVE',
                    'gold': (1, 5),
                    'loot_chance': 0.1,
                    'loot_table': ['potion_healing', 'short_sword'],
                    'depth': 3,
                    'biome': 'crypt',
                    'description': 'Оживлённые кости. Медлительны, но упрямы.',
                    'tags': ['undead', 'crypt']},
    'skeleton_archer': {   'char': 'A',
    'unicode_char': '🏹',
                           'name': 'скелет-лучник',
                           'color': 'cyan',
                           'hp': 10,
                           'atk': 1,
                           'dmg': (1, 4, 0),
                           'ac': 0,
                           'speed': 1.0,
                           'xp': 10,
                           'ai': 'RANGED',
                           'gold': (2, 6),
                           'loot_chance': 0.2,
                           'loot_table': ['potion_healing', 'bread'],
                           'depth': 3,
                           'biome': 'crypt',
                           'description': 'Худой лучник, предпочитающий держать дистанцию.',
                           'tags': ['undead', 'crypt']},
    'goblin_shaman': {   'char': 'G',
    'unicode_char': '🧙',
                         'name': 'гоблин-шаман',
                         'color': 'magenta',
                         'hp': 14,
                         'atk': 1,
                         'dmg': (1, 4, 0),
                         'ac': 1,
                         'speed': 1.0,
                         'xp': 14,
                         'ai': 'CASTER',
                         'gold': (3, 8),
                         'loot_chance': 0.25,
                         'loot_table': ['potion_mana', 'spellbook_lightning', 'bread'],
                         'depth': 3,
                         'biome': 'dungeon',
                         'description': 'Гоблин, научившийся простым чарам. Бьёт молниями с расстояния.',
                         'tags': ['humanoid', 'mage', 'cave', 'dungeon']},
    'dark_priest': {   'char': 'P',
    'unicode_char': '⛓',
                       'name': 'тёмный жрец',
                       'color': 'black',
                       'hp': 20,
                       'atk': 2,
                       'dmg': (1, 5, 1),
                       'ac': 2,
                       'speed': 1.0,
                       'xp': 22,
                       'ai': 'CASTER',
                       'gold': (5, 15),
                       'loot_chance': 0.3,
                       'loot_table': ['potion_healing', 'potion_mana', 'spellbook_barrier'],
                       'depth': 4,
                       'biome': 'crypt',
                       'description': 'Служитель тёмных сил. Колдует болезненные проклятия и исцеляет себя.',
                       'tags': ['undead', 'mage', 'crypt']},
    'imp': {   'char': 'i',
    'unicode_char': '👿',
               'name': 'бес',
               'color': 'red',
               'hp': 8,
               'atk': 2,
               'dmg': (1, 4, 1),
               'ac': 0,
               'speed': 1.5,
               'xp': 11,
               'ai': 'RANGED',
               'gold': (2, 7),
               'loot_chance': 0.15,
               'loot_table': ['potion_healing'],
               'depth': 3,
               'biome': 'hell',
               'description': 'Маленький демон, швыряющийся огненными искрами.',
               'tags': ['demon', 'hell', 'flying', 'fire']},
    'necromancer': {   'char': 'N',
    'unicode_char': '🔮',
                       'name': 'некромант',
                       'color': 'magenta',
                       'hp': 16,
                       'atk': 2,
                       'dmg': (1, 6, 1),
                       'ac': 1,
                       'speed': 1.0,
                       'xp': 18,
                       'ai': 'RANGED',
                       'gold': (5, 15),
                       'loot_chance': 0.3,
                       'loot_table': ['potion_healing', 'bread'],
                       'depth': 4,
                       'biome': 'crypt',
                       'description': 'Тёмный маг, призывающий мёртвых. Держится подальше от врага.',
                       'tags': ['undead', 'mage', 'crypt']},
    'ogre': {   'char': 'O',
    'unicode_char': '🧌',
                'name': 'огр',
                'color': 'green',
                'hp': 30,
                'atk': 3,
                'dmg': (2, 5, 2),
                'ac': 3,
                'speed': 0.7,
                'xp': 25,
                'ai': 'AGGRESSIVE',
                'gold': (5, 12),
                'loot_chance': 0.25,
                'loot_table': ['potion_healing', 'short_sword', 'leather_armor'],
                'depth': 4,
                'biome': 'dungeon',
                'description': 'Огромный тупица с дубиной. Медленный, но одним ударом может убить.',
                'tags': ['humanoid', 'cave']},
    'troll': {   'char': 'T',
    'unicode_char': '🧟',
                 'name': 'тролль',
                 'color': 'green',
                 'hp': 35,
                 'atk': 4,
                 'dmg': (2, 6, 2),
                 'ac': 4,
                 'speed': 0.8,
                 'xp': 35,
                 'ai': 'AGGRESSIVE',
                 'gold': (8, 20),
                 'loot_chance': 0.3,
                 'loot_table': ['potion_healing', 'bread'],
                 'depth': 5,
                 'biome': 'caves',
                 'description': 'Толстокожий великан. Невероятно живуч.',
                 'tags': ['humanoid', 'cave']},
    'zombie': {   'char': 'Z',
    'unicode_char': '🧟',
                  'name': 'зомби',
                  'color': 'green',
                  'hp': 20,
                  'atk': 2,
                  'dmg': (1, 5, 1),
                  'ac': 0,
                  'speed': 0.5,
                  'xp': 8,
                  'ai': 'STATIONARY',
                  'gold': (0, 3),
                  'loot_chance': 0.05,
                  'loot_table': ['potion_healing'],
                  'depth': 2,
                  'biome': 'crypt',
                  'description': 'Медлительный мертвец. Не двигается, пока не почувствует добычу рядом.',
                  'tags': ['undead', 'crypt']},
    'wolf': {   'char': 'w',
    'unicode_char': '🐺',
                'name': 'серый волк',
                'color': 'white',
                'hp': 12,
                'atk': 2,
                'dmg': (1, 5, 0),
                'ac': 1,
                'speed': 1.3,
                'xp': 9,
                'ai': 'PACK',
                'gold': (0, 4),
                'loot_chance': 0.1,
                'loot_table': ['bread'],
                'depth': 2,
                'biome': 'caves',
                'description': 'Хищник, охотящийся стаей. Рядом с сородичами становится агрессивнее.',
                'tags': ['beast', 'cave']},
    'gelatinous_cube': {   'char': 'Q',
    'unicode_char': '🧊',
                           'name': 'желеобразный куб',
                           'color': 'cyan',
                           'hp': 22,
                           'atk': 2,
                           'dmg': (1, 6, 1),
                           'ac': 2,
                           'speed': 0.6,
                           'xp': 14,
                           'ai': 'WANDERING',
                           'gold': (1, 6),
                           'loot_chance': 0.2,
                           'loot_table': ['potion_healing', 'bread'],
                           'depth': 3,
                           'biome': 'sewers',
                           'description': 'Полупрозрачный куб слизи. Поглощает всё на своём пути.',
                           'tags': ['aberration', 'cave']},
    'archmage': {   'char': 'M',
    'unicode_char': '🧙',
                    'name': 'архимаг',
                    'color': 'magenta',
                    'hp': 35,
                    'atk': 3,
                    'dmg': (1, 6, 2),
                    'ac': 3,
                    'speed': 1.1,
                    'xp': 55,
                    'ai': 'CASTER',
                    'gold': (10, 30),
                    'loot_chance': 0.5,
                    'loot_table': ['potion_mana', 'potion_mana', 'spellbook_fireball', 'spellbook_invisibility'],
                    'depth': 5,
                    'biome': 'dungeon',
                    'description': 'Величайший маг подземелья. Владеет разрушительной магией.',
                    'tags': ['humanoid', 'mage', 'deep']},
    'ancient_lich': {   'char': 'L',
    'unicode_char': '☠',
                        'name': 'древний лич',
                        'color': 'cyan',
                        'hp': 50,
                        'atk': 5,
                        'dmg': (2, 6, 3),
                        'ac': 4,
                        'speed': 0.9,
                        'xp': 120,
                        'ai': 'CASTER',
                        'gold': (25, 60),
                        'loot_chance': 0.6,
                        'loot_table': ['potion_mana', 'spellbook_teleport', 'spellbook_ice_bolt', 'spellbook_haste'],
                        'depth': 6,
                        'biome': 'crypt',
                        'description': 'Неживой владыка магии. Способен вызвать огненный шар и телепортироваться.',
                        'tags': ['undead', 'mage', 'deep']},
    'vampire': {   'char': 'V',
    'unicode_char': '🧛',
                   'name': 'вампир',
                   'color': 'red',
                   'hp': 40,
                   'atk': 4,
                   'dmg': (2, 6, 2),
                   'ac': 3,
                   'speed': 1.2,
                   'xp': 60,
                   'ai': 'AGGRESSIVE',
                   'gold': (15, 40),
                   'loot_chance': 0.5,
                   'loot_table': ['potion_healing', 'short_sword', 'leather_armor', 'bread'],
                   'depth': 5,
                   'biome': 'crypt',
                   'description': 'Благородный нежить. Восстанавливает здоровье, нанося урон.',
                   'tags': ['undead', 'vampire', 'crypt']},
    'dragon_whelp': {   'char': 'D',
    'unicode_char': '🐉',
                        'name': 'дракончик',
                        'color': 'red',
                        'hp': 50,
                        'atk': 5,
                        'dmg': (2, 8, 3),
                        'ac': 5,
                        'speed': 1.0,
                        'xp': 100,
                        'ai': 'RANGED',
                        'gold': (30, 80),
                        'loot_chance': 0.7,
                        'loot_table': ['potion_healing', 'short_sword', 'leather_armor', 'bread'],
                        'depth': 6,
                        'biome': 'hell',
                        'description': 'Молодой дракон. Его огненное дыхание опасно на любом расстоянии.',
                        'tags': ['dragon', 'hell', 'fire']},

    'kobold': {'char': 'k',
    'unicode_char': '🦎',
               'name': 'кобольд',
               'color': 'yellow',
               'hp': 10,
               'atk': 1,
               'dmg': (1, 4, 0),
               'ac': 1,
               'speed': 1.1,
               'xp': 8,
               'ai': 'COWARDLY',
               'gold': (2, 6),
               'loot_chance': 0.15,
               'loot_table': ['potion_healing', 'dagger'],
               'depth': 3,
               'biome': 'caves',
               'description': 'Хитрый пещерный головорез. При ранении пытается убежать.',
               'tags': ['humanoid', 'cave']},
    'troglodyte': {'char': 't',
    'unicode_char': '🦎',
                   'name': 'троглодит',
                   'color': 'green',
                   'hp': 20,
                   'atk': 2,
                   'dmg': (1, 6, 1),
                   'ac': 2,
                   'speed': 0.9,
                   'xp': 14,
                   'ai': 'AGGRESSIVE',
                   'gold': (2, 8),
                   'loot_chance': 0.15,
                   'loot_table': ['potion_healing', 'bread'],
                   'depth': 4,
                   'biome': 'caves',
                   'description': 'Рептилия из глубоких пещер. Живуч и зол.',
                   'tags': ['humanoid', 'cave']},
    'cave_spider': {'char': 'X',
    'unicode_char': '🕷',
                    'name': 'пещерный паук',
                    'color': 'white',
                    'hp': 12,
                    'atk': 1,
                    'dmg': (1, 4, 0),
                    'ac': 1,
                    'speed': 1.2,
                    'xp': 10,
                    'ai': 'WANDERING',
                    'gold': (0, 3),
                    'loot_chance': 0.1,
                    'loot_table': ['potion_healing'],
                    'depth': 3,
                    'biome': 'caves',
                    'description': 'Ядовитый паук, плетущий ловчие сети.',
                    'tags': ['beast', 'cave', 'poisonous']},
    'drowned': {'char': 'd',
    'unicode_char': '🌊',
                'name': 'утопленник',
                'color': 'cyan',
                'hp': 24,
                'atk': 3,
                'dmg': (1, 6, 1),
                'ac': 0,
                'speed': 0.6,
                'xp': 16,
                'ai': 'AGGRESSIVE',
                'gold': (1, 5),
                'loot_chance': 0.1,
                'loot_table': ['potion_healing'],
                'depth': 7,
                'biome': 'crypt',
                'description': 'Мертвец, утонувший в водах склепа.',
                'tags': ['undead', 'crypt']},
    'ghost': {'char': 'h',
    'unicode_char': '👻',
              'name': 'призрак',
              'color': 'white',
              'hp': 18,
              'atk': 2,
              'dmg': (1, 5, 1),
              'ac': 4,
              'speed': 1.0,
              'xp': 25,
              'ai': 'WANDERING',
              'gold': (3, 10),
              'loot_chance': 0.2,
              'loot_table': ['potion_mana', 'scroll_magic_missile'],
              'depth': 8,
              'biome': 'crypt',
              'description': 'Бестелесный дух. Его прикосновение леденит кровь.',
              'tags': ['undead', 'crypt', 'flying']},
    'myconid': {'char': 'm',
    'unicode_char': '🍄',
                'name': 'мирконид',
                'color': 'magenta',
                'hp': 14,
                'atk': 1,
                'dmg': (1, 4, 1),
                'ac': 1,
                'speed': 0.8,
                'xp': 12,
                'ai': 'STATIONARY',
                'gold': (1, 5),
                'loot_chance': 0.15,
                'loot_table': ['potion_healing', 'potion_mana', 'mushroom'],
                'depth': 9,
                'biome': 'mushroom_forest',
                'description': 'Разумный гриб. Выпускает облако спор при опасности.',
                'tags': ['mushroom', 'poisonous']},
    'shambler': {'char': 'F',
    'unicode_char': '🍂',
                 'name': 'шамблер',
                 'color': 'green',
                 'hp': 28,
                 'atk': 3,
                 'dmg': (2, 5, 1),
                 'ac': 2,
                 'speed': 0.6,
                 'xp': 22,
                 'ai': 'AGGRESSIVE',
                 'gold': (2, 8),
                 'loot_chance': 0.2,
                 'loot_table': ['potion_healing', 'mushroom'],
                 'depth': 8,
                 'biome': 'mushroom_forest',
                 'description': 'Грибковый голем, медленно преследующий добычу.',
                 'tags': ['mushroom', 'poisonous']},
    'demon': {'char': '6',
    'unicode_char': '👹',
              'name': 'демон',
              'color': 'red',
              'hp': 35,
              'atk': 4,
              'dmg': (2, 6, 2),
              'ac': 3,
              'speed': 1.1,
              'xp': 45,
              'ai': 'AGGRESSIVE',
              'gold': (10, 25),
              'loot_chance': 0.3,
              'loot_table': ['potion_healing', 'potion_mana'],
              'depth': 11,
              'biome': 'hell_forge',
              'description': 'Существо из пламени ада. Обжигает всё вокруг.',
              'tags': ['demon', 'hell', 'fire']},
    'fire_elemental': {'char': 'E',
    'unicode_char': '🔥',
                       'name': 'огненный элементаль',
                       'color': 'yellow',
                       'hp': 40,
                       'atk': 5,
                       'dmg': (2, 8, 2),
                       'ac': 2,
                       'speed': 1.2,
                       'xp': 60,
                       'ai': 'AGGRESSIVE',
                       'gold': (12, 30),
                       'loot_chance': 0.35,
                       'loot_table': ['potion_mana', 'scroll_fireball'],
                       'depth': 12,
                       'biome': 'hell_forge',
                       'description': 'Живое пламя. Невосприимчив к огню.',
                       'tags': ['elemental', 'hell', 'fire']},
    'shadow': {'char': 'x',
    'unicode_char': '🌑',
               'name': 'тень',
               'color': 'black',
               'hp': 22,
               'atk': 3,
               'dmg': (1, 6, 2),
               'ac': 6,
               'speed': 1.3,
               'xp': 40,
               'ai': 'WANDERING',
               'gold': (5, 15),
               'loot_chance': 0.25,
               'loot_table': ['potion_mana', 'scroll_teleport'],
               'depth': 14,
               'biome': 'deep_dark',
               'description': 'Тень, отделившаяся от своего хозяина. Почти неуловима.',
               'tags': ['undead', 'deep']},
    'aberration': {'char': 'A',
    'unicode_char': '🏹',
                   'name': 'аберрация',
                   'color': 'magenta',
                   'hp': 55,
                   'atk': 6,
                   'dmg': (3, 6, 3),
                   'ac': 3,
                   'speed': 0.9,
                   'xp': 90,
                   'ai': 'CASTER',
                   'gold': (20, 50),
                   'loot_chance': 0.4,
                   'loot_table': ['potion_mana', 'potion_mana', 'spellbook_teleport'],
                   'depth': 15,
                   'biome': 'deep_dark',
                   'description': 'Чудовище из бездны. Обладает психической магией.',
                   'tags': ['aberration', 'deep', 'mage']},
    'mimic': {'char': 'C',
    'unicode_char': '👅',
              'name': 'мимик',
              'color': 'yellow',
              'hp': 40,
              'atk': 3,
              'dmg': (2, 6, 2),
              'ac': 3,
              'speed': 1.0,
              'xp': 50,
              'ai': 'AGGRESSIVE',
              'gold': (20, 50),
              'loot_chance': 0.8,
              'loot_table': ['potion_healing_major', 'potion_mana', 'scroll_fireball'],
              'depth': 5,
              'biome': 'dungeon',
              'description': 'Чудовище, притворяющееся сундуком.',
              'tags': ['dungeon', 'aberration']},
}


def get_monster(monster_id: str) -> dict | None:
    return MONSTERS.get(monster_id)


def monsters_for_depth(depth: int, biome: str | None = None) -> list[str]:
    """Вернуть ID монстров, подходящих для глубины (и опционально биома)."""
    result = []
    for mid, data in MONSTERS.items():
        # Допускаем монстров глубины [depth-1, depth+1]
        if data["depth"] <= depth + 1 and data["depth"] >= max(1, depth - 1):
            if biome is None or data.get("biome") == biome:
                result.append(mid)
    return result


def monsters_for_biome(biome_tags: list[str], depth: int) -> list[str]:
    """Вернуть ID монстров, подходящих для биома и глубины."""
    result = []
    biome_set = set(biome_tags)
    for mid, data in MONSTERS.items():
        if data["depth"] > depth + 1 or data["depth"] < max(1, depth - 1):
            continue
        mob_tags = set(data.get("tags", []))
        if not (mob_tags & biome_set):
            continue
        result.append(mid)
    return result if result else monsters_for_depth(depth)
